adding support for 2.x -> 4.x migrations
CircleCI-Public/server-scripts pull request #35
Opened 2022-10-03 17:44 UTC by soulchips

:gear: **Issue**
https://circleci.atlassian.net/browse/SERVER-2082

In server 4.x, the structure of the postgres secret has changed which blocks migration from 2.x to 4.x directly with our scripts

:white_check_mark: **Fix**

Added a `--server4` flag which will account for the postgres change in 4.x

:question: **Tests**

- [ ] Tested Updating Existing Instance
- [ ] Installed on new instance

2022-10-04 12:42 UTC, lloydChris requested changes

2022-10-04 12:42 UTC, lloydChris commented on migrate/3.0-restore.sh
> +        # reinject_bottoken
was this an accidental commit?

2022-10-05 16:08 UTC, soulchips commented on migrate/3.0-restore.sh
> +        # reinject_bottoken
yes thank you for catching.

2022-10-11 16:19 UTC, ryanwohara approved these changes

2022-10-11 17:05 UTC, atulsingh0 approved these changes

2022-10-13 18:43 UTC, merged